### ISSUE TITLE
三角在右侧时出错了。。。

### ISSUE THREAD

**Issue by syg13579** [nyakokishi/ChatImageView#1]
右侧画右上角应该是：path.arcTo(new RectF(rectF.right - mArrowWidth - 2 * mRadius, rectF.top
                , rectF.right - mArrowWidth, rectF.top + 2 * mRadius), 270, 90);
源码是：path.arcTo(new RectF(rectF.right - mArrowWidth - 2 * mRadius, rectF.top
                , rectF.right - mArrowHeight, rectF.top + 2 * mRadius), 270, 90);

**Comment by nyakokishi** [comment]
@syg13579 已修复，感谢指出错误
